# Generated by Django 4.0.3 on 2022-10-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='winner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
