# Generated by Django 4.0.3 on 2022-10-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20220817_1510'),
        ('auctions', '0007_user_phone_number'),
    ]

    operations = [
    ]
