# Generated by Django 4.0.3 on 2022-10-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_merge_0006_auto_20220817_1510_0007_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image_link',
        ),
        migrations.AddField(
            model_name='listing',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
