# Generated by Django 4.0.3 on 2022-10-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listing_image_link_listing_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image_file',
            new_name='imgfile',
        ),
    ]
