# Generated by Django 4.0.3 on 2022-10-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_user_notify_winner_phone_number'),
        ('auctions', '0010_rename_image_file_listing_imgfile'),
    ]

    operations = [
    ]
