# Generated by Django 4.0.3 on 2022-10-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_merge_20221014_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='imgfile',
        ),
        migrations.AddField(
            model_name='listing',
            name='image_link',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
